// This file is automatically generated. Do not modify it manually.

const manifest = JSON.parse(`
{
    "id": "com.mattermost.voice",
    "name": "Voice",
    "description": "Mattermost plugin to enable voice messaging.",
    "homepage_url": "https://github.com/streamer45/mattermost-plugin-voice",
    "support_url": "https://github.com/streamer45/mattermost-plugin-voice/issues",
    "version": "0.4.0",
    "min_server_version": "11.0.0",
    "server": {
        "executables": {
            "darwin-amd64": "server/dist/plugin-darwin-amd64",
            "darwin-arm64": "server/dist/plugin-darwin-arm64",
            "linux-amd64": "server/dist/plugin-linux-amd64",
            "linux-arm64": "server/dist/plugin-linux-arm64",
            "windows-amd64": "server/dist/plugin-windows-amd64.exe"
        },
        "executable": ""
    },
    "webapp": {
        "bundle_path": "webapp/dist/main.js"
    },
    "settings_schema": {
        "header": "",
        "footer": "",
        "settings": [
            {
                "key": "VoiceMaxDuration",
                "display_name": "Max Duration",
                "type": "number",
                "help_text": "Max duration allowed (in seconds) for voice messages.",
                "placeholder": "",
                "default": 300,
                "hosting": "",
                "secret": false
            },
            {
                "key": "VoiceAudioBitrate",
                "display_name": "Audio Quality",
                "type": "dropdown",
                "help_text": "Audio quality of voice messages. This setting affects recording size.",
                "placeholder": "",
                "default": "64",
                "options": [
                    {
                        "display_name": "High (128 kbps)",
                        "value": "128"
                    },
                    {
                        "display_name": "Normal (64 kbps)",
                        "value": "64"
                    },
                    {
                        "display_name": "Low (48 kbps)",
                        "value": "48"
                    }
                ],
                "hosting": "",
                "secret": false
            }
        ],
        "sections": null
    }
}
`);

export default manifest;
export const id = manifest.id;
export const version = manifest.version;
export const pluginId = manifest.id;
